# Generated by Django 4.2.16 on 2024-11-02 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_global_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('issue', models.CharField(max_length=500, verbose_name='Issue Details')),
                ('priority', models.CharField(max_length=10, verbose_name='Priority')),
                ('ticket_number', models.IntegerField(verbose_name='Ticket Number')),
                ('raised_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
