# Generated by Django 4.2.16 on 2024-11-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='status',
            field=models.CharField(blank=True, choices=[('Reported', 'Reported'), ('In Progress', 'In Progress'), ('Solved', 'Solved')], default='Reported', max_length=30, null=True, verbose_name='Status'),
        ),
    ]
