# Generated by Django 4.2.16 on 2024-11-03 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 19, 3, 19, 654813, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
