# Generated by Django 4.2.16 on 2024-11-05 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_model_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 17, 11, 15, 805349, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
