# Generated by Django 4.2.16 on 2024-11-06 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_model_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 16, 9, 4, 972910, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
    ]
