# Generated by Django 4.2.16 on 2024-11-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user_model',
            name='username',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='custom_user_model',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
