# Generated by Django 4.2.16 on 2024-11-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_custom_user_model_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='global_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('phone', models.IntegerField(verbose_name='Number:')),
                ('fb_link', models.CharField(max_length=250, verbose_name='FACEBOOK LINK:')),
                ('insta_link', models.CharField(max_length=250, verbose_name='INSTAGRAM LINK:')),
            ],
        ),
    ]
