# Generated by Django 4.2.16 on 2024-11-04 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_model_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 17, 56, 17, 227205, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='ticket_model',
            name='priority',
            field=models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True, verbose_name='Priority'),
        ),
    ]
